### ISSUE TITLE
I run this on windows 10 by helping git and python 3.7 then it show

### ISSUE THREAD

**Issue by Ankur4299** [lfasmpao/box.com-downloader#3]
C:\Users\Ankur>git clone https://github.com/lfasmpao/box.com-downloader
Cloning into 'box.com-downloader'...
remote: Enumerating objects: 29, done.
Uremote: Total 29 (delta 0), reused 0 (delta 0), pack-reused 29
Unpacking objects: 100% (29/29), done.

C:\Users\Ankur>cd box.com-downloader

C:\Users\Ankur\box.com-downloader>pip install -r requirements.txt
Requirement already satisfied: PyVirtualDisplay==0.2.1 in c:\program files\python37\lib\site-packages (from -r requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: selenium==3.14.0 in c:\program files\python37\lib\site-packages (from -r requirements.txt (line 2)) (3.14.0)
Requirement already satisfied: EasyProcess in c:\program files\python37\lib\site-packages (from PyVirtualDisplay==0.2.1->-r requirements.txt (line 1)) (0.2.7)
Requirement already satisfied: urllib3 in c:\program files\python37\lib\site-packages (from selenium==3.14.0->-r requirements.txt (line 2)) (1.25.3)

C:\Users\Ankur\box.com-downloader>python main.py https://app.box.com/s/hs5de51wub2htrcl0hxn1wir4zpmf3wj
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Box.com PDF Downloader by @lfasmpao
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Program Files\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 44, in main
    box_object = Scraper(args.url, args.driver_location, args.use_x11, args.wait_time)
  File "C:\Users\Ankur\box.com-downloader\scraper.py", line 78, in __init__
    self.driver_obj = webdriver.Chrome(self.driver_location, chrome_options=chrome_options)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by lfasmpao** [comment]
It seems like you don't have webdriver installed or you didn't set it up properly. Kindly check this video tutorial on how to setup selenium chrome webdriver on windows. https://youtu.be/dz59GsdvUF8

**Comment by Ankur4299** [comment]
![chromedriver](https://user-images.githubusercontent.com/51435336/59141252-ea1b1f80-89db-11e9-82f0-c9c55aaad804.jpg)
![app box](https://user-images.githubusercontent.com/51435336/59141256-f30bf100-89db-11e9-9166-30fa2a1de4d9.jpg)

sir, same error occurred. i watch the video and do exactly which is they told. but my problem is not properly solved.
