### ISSUE TITLE
Download URL: None

### ISSUE THREAD

**Issue by Ankur4299** [lfasmpao/box.com-downloader#4]
![location](https://user-images.githubusercontent.com/51435336/60393087-c5e3c780-9add-11e9-9fc2-c2d5be146e17.png)
![cmd](https://user-images.githubusercontent.com/51435336/60393094-e01da580-9add-11e9-8ded-25c427630b3c.png)

**Comment by Ankur4299** [comment]
sir, Please HElP me this is most important for me and this error occured

**Comment by Ankur4299** [comment]
https://app.box.com/embed/s/erzvmgoqinlw0c9e6ni7i4c8k4l9710h

**Comment by Ankur4299** [comment]
https://app.box.com/s/erzvmgoqinlw0c9e6ni7i4c8k4l9710h

**Comment by master0044657** [comment]
It gives me the exact same error on other pdfs. App is broken.

**Comment by lfasmpao** [comment]
Hello there, they updated the way they distribute the document that is why you got the **None**. I'll provide a new way to scrape. Thanks

**Comment by lfasmpao** [comment]
The issue has been fixed on the latest commit:
https://github.com/lfasmpao/box.com-downloader/commit/2bef9112c418b413acd77eabed91afeeaf5251d2

Thanks
